@startuml

package sample <<Folder>>{
package schemes <<Folder>>{
class Scheme extends javafx.scene.Group
class Branch implements SchemeBuilder
class Cycle implements SchemeBuilder
class Linear implements SchemeBuilder
interface SchemeBuilder
package nodes <<Folder>>{
class Begin extends javafx.scene.shape.Circle
class End
class Solution extends javafx.scene.shape.Rectangle
class Operation extends javafx.scene.shape.Rectangle
class Arrows
}
}
class Main extends javafx.application.Application
class Controller
class Director
}

@enduml